export const SUBMIT_CITY = 'SUBMIT_CITY';
export const SUBMIT_CITY_START = 'SUBMIT_CITY_START';
export const SUBMIT_CITY_SUCCESS = 'SUBMIT_CITY_SUCCESS';
export const SUBMIT_CITY_FAILED = 'SUBMIT_CITY_FAILED';
